spring.application.name=im.db.api
server.port=8082
server.address=0.0.0.0

jasypt.encryptor.password=imanager-secret
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname: org.jasypt.iv.NoIvGenerator 

spring.datasource.url=jdbc:postgresql://ep-shrill-cherry-a1jz2hot-pooler.ap-southeast-1.aws.neon.tech/iManager?sslmode=require
spring.datasource.username=ENC(xIP0enVLXP+/Isl5GRN1SYbN9xgkl7Z5)
spring.datasource.password=ENC(y/5BVT5dVYmnXSyJu5LiX78nVFghb94d/XYWRPtC7/Y=)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=20


# Required connection configs for Kafka producer, consumer, and admin
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='QZUUVRUW44VBPM4K' password='USjKznljTpW7/AH7weOE2iioWVh0UbdQ9vxjYqM8XJGWyH6x/4PtseTtHccsaaQh';
spring.kafka.properties.security.protocol=SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
session.timeout.ms=45000


spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Producer-Properties
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=springboot-group-1

client.id=ccloud-springboot-client-83e6df56-7f99-469f-b3b7-45dcd89a2ec5

#Github
github.client.id=ENC(KRNgag7u1MuJVthUhhtG+MElj6EepD9Q8HsnVFsjCLI=)
github.client.secret=ENC(GQYRyWYhCHHdwY2e1sYom7ZKTzYAxj7kzsghLl7iRbon5ncII/YjeRQXzSrb9vr/2K9jhS+vjLs=)
github.redirect.uri=https://imanager.vercel.app/dashboard
github.webhook=http://65.0.180.182:8082/api/github/webhook


